language: python
python: 3.5.3

install:
    - pip install -r envrequirements.txt


before_script:
  - wget https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.5.3/bin
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
          
script:
    behave features/
          
    