language: python
python: 3.5


_browsers:
  chrome: &chrome
    addons:
      apt:
        packages:
          - google-chrome-stable
          
          
script:
    behave features/
          
    