language: python
python: 3.5

install:
    - pip install -r envrequirements.txt

_browsers:
  chrome: &chrome
    addons:
      apt:
        packages:
          - google-chrome-stable
          
matrix:
    
          
script:
    behave features/
          
    