language: python
python: 3.5

sudo: required
env: DISPLAY=':99.0'
dist: trusty

install:
    - pip install -r envrequirements.txt

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - sh -e /etc/init.d/xvfb start      
          
script:
    behave features/
          
    