'''
Created on Apr 3, 2017

@author: csantoso
'''


HOME_URL_PATH = "https://truva.id"
EXT_CARI_URL_PATH = "/cari/"
EXT_JUAL_URL_PATH = "/jual/"
EXT_CARA_URL_PATH = "/cara-kerja/"
EXT_TENTANG_URL_PATH = "/tentang/"


HOME_TEST_CASE = "HOME" 
FIND_TEST_CASE = "FIND" 

MARKET_PRICE_OPTION_BRAND = "brand"
MARKET_PRICE_OPTION_MODEL = "model"
MARKET_PRICE_OPTION_YEAR = "year"
MARKET_PRICE_OPTION_VARIANT = "variant"

CAN_SEE_4_TABS = "CAN SEE 4 TABS"
CAN_SEE_CAROUSEL = "CAN SEE CAROUSEL"
CAN_SEE_INSPECTION_WORK = "CAN SEE INSPECTION"
CAN_SEE_8_OFFERS = "CAN SEE 8 OFFERS"
CAN_SEE_MARKET_PRICE = "CAN SEE MARKET PRICE"
CAN_SEE_10_ARTICLES = "CAN SEE 10 ARTICLES"

CAN_SEE_4_TABS_CARI_MOBIL = "CARI MOBIL"
CAN_SEE_4_TABS_JUAL_MOBIL = "JUAL MOBIL"
CAN_SEE_4_TABS_CARA_KERJA = "CARA KERJA"
CAN_SEE_4_TABS_TENTANG_TRUVA = "TENTANG TRUVA"
CAN_SEE_4_TABS_TOTAL_TABS = 4

CAN_SEE_INSPECTION_WORK_APA_SAJA_YANG_KAMI_INSPEKSI = "APA SAJA YANG KAMI INSPEKSI?"

DATE_FORMAT_FILE = "%Y.%m.%d_%H.%M.%S"
DATE_FORMAT_LOG = "%Y.%m.%d %H:%M:%S"

RUN_THE_FILTER = "RUN THE FILTER"

CHOOSE_FILTER_VALUE = "CHOOSE FILTER VALUE"

FIND_OPTION_BRAND = "brand"
FIND_OPTION_TRANSMISSION = "transmission"
FIND_OPTION_LOCATION = "location"
FIND_OPTION_SCORE = "score"
FIND_OPTION_PRICE = "price"
FIND_OPTION_PRICE_ORDER = "price_order"
